# Generated by Django 5.1.6 on 2025-04-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="extra_info",
        ),
        migrations.AddField(
            model_name="car",
            name="extra_info_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Extra Info (English)"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="extra_info_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Extra Info (Español)"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="extra_info_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Extra Info (French)"
            ),
        ),
    ]
