# Generated by Django 5.1.6 on 2025-05-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0003_remove_driver_extra_info_driver_extra_info_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25, verbose_name="Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("opinion", models.TextField(verbose_name="Opinion")),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
