# Generated by Django 5.1.6 on 2025-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0004_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSiteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitors_counter", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Global Site Data",
            },
        ),
    ]
